const titles = [
  "Midnight Whispers", "Summer Breeze", "Dancing Shadows", "Forgotten Dreams", "Starlit Serenade",
  "Echoes of Yesterday", "Enchanted Melodies", "Crystal Waters", "Wandering Soul", "Sunshine Smiles",
  "Raindrop Lullaby", "Painted Skies", "Serendipity", "Whispers in the Wind", "Ocean's Embrace",
  "Moonlit Memories", "Velvet Silence", "Secret Garden", "Rustling Leaves", "Solitude's Symphony",
  "Firefly Waltz", "Paper Airplanes", "Lost and Found", "Harbor of Hope", "Melancholy Melodies",
  "Carousel Dreams", "Heartstrings Harmony", "Wanderlust", "Gentle Reminders", "Dreamscape Reverie",
  "Sunflower Serenade", "Rustic Romance", "Butterfly Kisses", "Autumn Serenity", "Stargazer's Ballad",
  "Floating on Air", "Whimsical Whistler", "Lemonade Skies", "Seafoam Serenade", "Daybreak Delight",
  "Mountain Melodies", "Wishing Well", "Meadow Musings", "Carnival Carousel", "Riverside Rhapsody",
  "Willow's Whisper", "Sun-kissed Serenade", "Featherlight", "Harbor Lights", "Cloud Dancer",
  "Radiant Echoes", "Pebble Pathways", "Celestial Serenity", "Lullaby Lane", "Echoing Laughter",
  "Evening Embrace", "Painted Horizons", "Sunkissed Serenade", "Starry-eyed Soiree",
  "Velvet Moonrise","Firelight Fables", "Whistling Willow", "Moonbeam Melodies", "Harbor Breeze",
  "Cobblestone Chronicles", "Enchanted Twilight", "Rustic Whispers", "Ocean's Lullaby", "Silent Echo",
  "Serenade of Dreams", "Dandelion Wishes", "Rainy Day Reverie", "Sunset Sonata", "Candlelit Confessions",
  "Meadow's Grace", "Skipping Stones", "Starlit Whispers", "Daydreamer's Diary", "Secret Admirer",
  "Cloud Castle", "Whistling Winds", "Crystal Cascade", "Evening Euphoria", "Radiant Reflections",
  "Moonlit Mosaic", "Serene Skylines", "Lighthouse Lullaby", "Ember's Embrace", "Enchanted Oasis",
  "Riverbank Reverie", "Twilight Tango", "Fireside Serenade", "Hidden Treasures", "Cobblestone Serenity",
  "Dreamcatcher's Lullaby", "Carousel of Stars", "Meadow Melodies", "Raindrop Rendezvous", "Ocean Odyssey",
  "Sunflower Sonata", "Riverside Romance", "Feathered Friends", "Stargazer's Serenade", "Echoes of Eternity",
  "Daylight Dreams", "Midnight Muse", "Painted Promises", "Dancing Rainbows",
  "Enchanted Escapade", "Crystal Carousel", "River of Dreams", "Twilight Trails", "Serenade of Seasons",
  "Moonlit Magic", "Fireside Tales", "Starlit Secrets", "Meadow Memoirs", "Ocean Serenity", "Rustic Reverie",
  "Whispering Willow", "Sun-kissed Secrets", "Enchanted Embers", "Pebble Path", "Daybreak Delights",
  "Carnival of Colors", "Whispering Windchimes", "Secret Sanctuary", "Moonbeam Musings", "Fireside Flair",
  "Harbor Harmony", "Wandering Hearts", "Meadow Mystique", "Riverside Rhapsodies", "Celestial Symphony",
  "Rustic Reflections", "Ocean's Overture", "Dusk's Embrace", "Echoing Dreams", "Starry Nights", "Midnight Melodies",
  "Summer Serenade", "Dancing Raindrops", "Forgotten Fantasies", "Crystal Caverns", "Wandering Wonder", 
  "Sunshine Serenity", "Rainy Day Reflections", "Painted Horizons", "Whispers in the Woods", "Ocean's Oasis",
  "Moonlit Musings", "Fireside Frolic", "Harbor Hearts", "Meadow Whispers", "Starlit Stories", "Rustic Reveries",
  "Enchanted Echo", "Twilight Tranquility", "Serenade of Sunflowers", "Midnight Memories", "Dreamer's Delight",
  "Crystal Cascades", "Whispering Waters", "Ocean Serenade", "Stargazer's Dream", "Fireside Fables", "Meadow Magic",
  "Riverside Rhythms", "Celestial Dreams", "Rustic Rendezvous", "Moonlit Mirage", "Sunshine Soiree", "Dusk's Serenade",
  "Enchanted Echoes", "Harbor Horizons", "Wandering Whispers", "Whispering Willows", "Ocean Odyssey", "Starry Nightfall",
  "Fireside Flamenco", "Meadow Melancholy", "Riverside Reflections", "Crystal Kaleidoscope", "Moonlit Meditations",
  "Rustic Radiance", "Twilight Tapestry", "Serenade of Shadows", "Enchanted Expedition", "Harbor of Hearts", "Dandelion Dreams",
  "Whispers in the Wild", "Ocean's Oracle", "Fireside Fantasia", "Meadow Muse", "Celestial Cascade", "Rustic Reverberations",
  "Moonlit Melancholy", "Sunshine Sonata", "Starry-Eyed Escapade", "Whispering Wonders", "Midnight Musings", "Enchanted Endeavors",
  "Harbor Hopes", "Oceanic Overture", "Fireside Frescoes", "Celestial Canvas", "Moonlit Minuets", "Meadow Medleys",
  "Rustic Reminiscence", "Serenade of Sunsets", "Echoing Euphoria", "Whispering Wanderlust", "Harbor Hymn", "Ocean Odyssey",
  "Fireside Fugue", "Celestial Chorus", "Moonlit Memories", "Meadow Memoirs", "Rustic Romance", "Serenade of Stars",
  "Whispering Whimsies", "Harbor Harmony", "Oceanic Opus", "Fireside Flamenco", "Celestial Conversations", "Moonlit Melodies",
  "Rustic Reveries", "Whispering Whispers", "Harbor Horizons", "Oceanic Odyssey", "Fireside Fantasia", "Celestial Caravan",
  "Moonlit Musings", "Rustic Remembrances", "Whispering Wind", "Harbor Harmony", "Ocean's Overture", "Fireside Fantasies",
  "Celestial Serenade", "Moonlit Memories", "Rustic Reverie", "Whispering Willows", "Harbor Hearts", "Oceanic Odyssey",
  "Fireside Flamenco", "Celestial Canvas", "Moonlit Minuets", "Rustic Romance", "Whispering Wilderness", "Harbor Harmony",
  "Ocean's Opus", "Fireside Fugue", "Celestial Chorus", "Moonlit Memories", "Rustic Reflections", "Whispering Waves", "Harbor Hopes",
  "Oceanic Oases", "Fireside Fantasia", "Celestial Conversations", "Moonlit Melodies", "Rustic Reveries", "Whispering Whispers", "Harbor Horizons",
  "Oceanic Odyssey", "Fireside Flamenco", "Celestial Caravan", "Moonlit Musings", "Rustic Remembrances", "Whispering Wind", "Harbor Harmony",
  "Ocean's Overture", "Fireside Fantasies", "Celestial Serenade", "Moonlit Memories", "Rustic Reverie", "Whispering Willows", "Harbor Hearts",
  "Oceanic Odyssey", "Fireside Flamenco", "Celestial Canvas", "Moonlit Minuets", "Rustic Romance", "Whispering Wilderness", "Harbor Harmony",
  "Ocean's Opus", "Fireside Fugue", "Celestial Chorus", "Moonlit Memories", "Rustic Reflections", "Whispering Waves", "Harbor Hopes",
  "Oceanic Oases", "Fireside Fantasia", "Celestial Conversations", "Moonlit Melodies", "Rustic Reveries", "Whispering Whispers", "Harbor Horizons",
  "Oceanic Odyssey", "Fireside Flamenco", "Celestial Caravan", "Moonlit Musings", "Rustic Remembrances", "Whispering Wind"
]

export default titles